# Generated by Django 5.0.2 on 2024-02-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.IntegerField()),
                ('OrganizationId', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Website', models.URLField()),
                ('Country', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Founded', models.IntegerField()),
                ('Industry', models.CharField(max_length=255)),
                ('NumberOfEmployees', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
