# Generated by Django 5.0.2 on 2024-02-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_data_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
